export const COLORS_CONFIG = {
  mainPageBg: '#4D426D',
  bgArrayColors: ['#D2B4DE', '#8B80B2', '#4D426D'],
  weekNumberBg: '#FFF5EE',
  timerBg: '#FFF5EE',
  iconColor: '#FFF5EE',
  text: '#291B4E',
  textClassName: 'text-[#291B4E]',
  headerTextClassName: 'text-[#FFF5EE]',
  dayPassiveBg: '#FFF5EE',
  dayPassiveBorderColor: '#4D426D',
  modalBgClassName: 'bg-[#8B80B2]',
  modalBgWrapperClassName: 'bg-[#4D426DA6]',
  breakPlitka: '#7FFFD4',
  defaultPlitka: '#FFF5EE',
  popUpWindowBgClassName: 'bg-[#756a9f]',
  popUpWindowTextClassName: 'text-[#FFF5EE]',
  popUpWindowArrowClassName: 'before:bg-[#756a9f]',
  modalCloseButtonClassName: 'text-[#FFF5EE] hover:bg-white/5 active:bg-white/10',
  sosComponentBg: '#FFF5EE',
};

export const GRADIENT_COLORS_CONFIG = {
  sosComponentBorder: ['#FFF281', '#D2B4DE', '#7FFFD4'],
  weekNumberBorder: ['#FFF281', '#D2B4DE'],
  timerBorder: ['#FFF281', '#D2B4DE'],
  dayActiveBg: ['#FFF281', '#FFF5EE', '#FFF5EE'],
  currentPlitka: [
    '#FFF5EE',
    '#FFF5EE',
    '#FFF5EE',
    '#FFF5EE',
    '#FFF5EE',
    '#FFF281',
    '#FFF5EE',
    '#FFF5EE',
    '#FFF5EE',
    '#FFF5EE',
    '#FFF5EE',
  ],
};
